server:
  port: 7082

spring:
  application:
    name: doctor-portal

zuul:
  routes:
    usermanagement-app:
      url:  http://localhost:8082
  host:
    connect-timeout-millis:  2000
    socket-timeout-millis:  5000

management:
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    health:
      show-details:  ALWAYS