server:
    port: 8083
    ssl:
      enabled:  true
      key-store: ssl_server.jks
      key-password:  manu123
    servlet:
      context-path: /springDataDemo
spring:
  application:
    name: spring-data-demo


  datasource:
    url: jdbc:mysql://localhost:3306/echeque_schema?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
